### ISSUE TITLE
Error code 15 when trying to parse a ktx file

### ISSUE THREAD

**Issue by ghost** [UberLambda/libktx-rs#1]
I'm trying to parse [this](https://github.com/KhronosGroup/Vulkan-Samples-Assets/blob/177aea4beaa264e6e9823c80d9d0460e61db222f/textures/uffizi_rgba16f_cube.ktx) ktx file using this code:

```
unsafe fn libktx_rs() {
    let data = std::fs::read("uffizi_rgba16f_cube.ktx").unwrap();
    let mut result = zeroed();
    dbg!(ktxTexture2_CreateFromMemory(
        data.as_ptr(),
        data.len(),
        ktxTextureCreateFlagBits_KTX_TEXTURE_CREATE_NO_FLAGS,
        &mut result
    ));
    let result = &*result;
    dbg!(result.numFaces);
    dbg!(result.numLayers);
    dbg!(result.numLevels);
}
```

But the call to createfrommemory returns error code 15. C++ code that uses libktx directly works fine:

https://github.com/KhronosGroup/Vulkan-Samples/tree/master/framework/scene_graph/components/image/ktx.cpp#L64

**Comment by UberLambda** [comment]
Hi, sorry for the delay - I'm currently on vacation and I didn't check GitHub in a while. I'll try and investigate ASAP!

**Comment by UberLambda** [comment]
It looks like the file in question is a KTX1 (screenshot below). Vulkan-samples is using a `ktxTexture_CreateFromMemory` call (which autodetects the version based on the magic number), but you are using <tt>ktxTexture<b>2</b>_CreateFromMemory</tt>!

Could you try with `ktxTexture_CreateFromMemory` or `ktxTexture1_CreateFromMemory`?

![image](https://user-images.githubusercontent.com/7994377/127784254-2d49cef4-fff0-42f3-b4ce-1505e79e6ed4.png)

**Comment by ghost** [comment]
It works now. Thanks.
